version: '3.5'

services:
  db:
    image: postgres:latest
    container_name: DevFreela-db
    restart: always
    hostname: localhost
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=DevFreela
    ports:
      - 5432:5432
    volumes:
      - DevFreela-db:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: DevFreela-rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - DevFreela-rabbitmq:/var/lib/rabbitmq

volumes:
  DevFreela-db:
  DevFreela-rabbitmq:
