version: '3.5'

services:
  db:
    image: postgres:latest
    container_name: DevFreela-db
    restart: always
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=DevFreela
    ports:
      - 5432:5432
    volumes:
      - DevFreela-db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d rinha" ]
      interval: 10s
      timeout: 5s
      retries: 3

  rabbitmq:
    image: rabbitmq:3-management
    container_name: DevFreela-rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - DevFreela-rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  api:
    build:
      context: .
      dockerfile: ./DevFreela.API/Dockerfile
    container_name: DevFreela-api
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "5000:5000"

  payments:
    build:
      context: .
      dockerfile: ./DevFreela.Messaging/Dockerfile
    container_name: DevFreela-payments
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "6000:6000"

volumes:
  DevFreela-db:
  DevFreela-rabbitmq:
